In [1]:
import numpy as np

In [2]:
#where method

In [3]:
marks = np.array([50,56,32,67,54,99,76])

In [5]:
np.where(marks >50, "pass" , " fail")#works as if else if marks greater than 50 then pass else fail

array([' fail', 'pass', ' fail', 'pass', 'pass', 'pass', 'pass'],
      dtype='<U5')

In [6]:
salary = np.array([10, 70, 80 ,90 ,45])

In [8]:
np.where(salary<50, salary * 1.1 , salary * 1.05)# increasing the salary using the where method

array([11. , 73.5, 84. , 94.5, 49.5])

In [11]:
arr = np.arange(1,101).reshape((10,10))

In [12]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [14]:
arr.T # transpose of a matrix

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [17]:
arr.transpose() #transpose using transpose method

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [18]:
array = np.array([1,3,5,6,7,10])

In [19]:
array.mean()

5.333333333333333

In [20]:
array.cumsum()#cumulative sum

array([ 1,  4,  9, 15, 22, 32], dtype=int32)

In [22]:
array.cumprod()#cumulative product

array([   1,    3,   15,   90,  630, 6300], dtype=int32)

In [23]:
#methods for boolean arrays

In [24]:
gender = np.array(['Male','Female','Male','Female','Male','Male'])

In [26]:
arr = gender == 'Male'
arr

array([ True, False,  True, False,  True,  True])

In [28]:
arr.sum()#total no of males in array

4

In [31]:
arr = gender == 'Female'
arr.any()#any checks if the value is present or not

True

In [33]:
arr.all()# checks if all the values are 'female' or not

False

In [34]:
arr =  np.array([2,4,6,8,10,12])

In [35]:
x = arr % 2 == 0

In [36]:
x.all()

True

In [37]:
arr

array([ 2,  4,  6,  8, 10, 12])

In [47]:
arr = np.array([9,34,5,73,24,6,7,2,3,5,4])

In [48]:
arr.sort() #inplace sorting

In [49]:
arr

array([ 2,  3,  4,  5,  5,  6,  7,  9, 24, 34, 73])

In [50]:
arr[::-1]#sorting in reverse order

array([73, 34, 24,  9,  7,  6,  5,  5,  4,  3,  2])

In [53]:
arr = np.array([11,11,23,34,23,55,4,3,21,21])

In [55]:
np.unique(arr)# prints only single occurence of each element

array([ 3,  4, 11, 21, 23, 34, 55])

In [56]:
#file input output

In [57]:
array = np.array([10,20,30,40,50,60,70,80])

In [61]:
np.save('data',array)#saving the array in a file named "data"

In [62]:
content = np.load('data.npy')#loading the data of that file

In [60]:
content

array([10, 20, 30, 40, 50, 60, 70, 80])

In [63]:
#saving multiple arrays

In [65]:
students =  np.array(['Ali','Sarim','Ahmed','Moosa','Bilal'])
marks = np.array([97,93,91,70,76])

In [75]:
np.savez('arrays',std=students,m=marks)#savez is used for saving multiple arrays into a file

In [76]:
results = np.load('arrays.npz')

In [77]:
results['std']

array(['Ali', 'Sarim', 'Ahmed', 'Moosa', 'Bilal'], dtype='<U5')

In [78]:
results['m']

array([97, 93, 91, 70, 76])

In [ ]:
#linear algebra operations

In [79]:
arr = np.arange(16).reshape(4,4)

In [80]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
arr.diagonal()

array([ 0,  5, 10, 15])