In [5]:
import numpy as np

In [2]:
#where method

In [3]:
marks = np.array([50,56,32,67,54,99,76])

In [5]:
np.where(marks >50, "pass" , " fail")#works as if else if marks greater than 50 then pass else fail

array([' fail', 'pass', ' fail', 'pass', 'pass', 'pass', 'pass'],
      dtype='<U5')

In [6]:
salary = np.array([10, 70, 80 ,90 ,45])

In [8]:
np.where(salary<50, salary * 1.1 , salary * 1.05)# increasing the salary using the where method

array([11. , 73.5, 84. , 94.5, 49.5])

In [11]:
arr = np.arange(1,101).reshape((10,10))

In [12]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [14]:
arr.T # transpose of a matrix

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [17]:
arr.transpose() #transpose using transpose method

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [18]:
array = np.array([1,3,5,6,7,10])

In [19]:
array.mean()

5.333333333333333

In [20]:
array.cumsum()#cumulative sum

array([ 1,  4,  9, 15, 22, 32], dtype=int32)

In [22]:
array.cumprod()#cumulative product

array([   1,    3,   15,   90,  630, 6300], dtype=int32)

In [23]:
#methods for boolean arrays

In [24]:
gender = np.array(['Male','Female','Male','Female','Male','Male'])

In [26]:
arr = gender == 'Male'
arr

array([ True, False,  True, False,  True,  True])

In [28]:
arr.sum()#total no of males in array

4

In [31]:
arr = gender == 'Female'
arr.any()#any checks if the value is present or not

True

In [33]:
arr.all()# checks if all the values are 'female' or not

False

In [34]:
arr =  np.array([2,4,6,8,10,12])

In [35]:
x = arr % 2 == 0

In [36]:
x.all()

True

In [37]:
arr

array([ 2,  4,  6,  8, 10, 12])

In [47]:
arr = np.array([9,34,5,73,24,6,7,2,3,5,4])

In [48]:
arr.sort() #inplace sorting

In [49]:
arr

array([ 2,  3,  4,  5,  5,  6,  7,  9, 24, 34, 73])

In [50]:
arr[::-1]#sorting in reverse order

array([73, 34, 24,  9,  7,  6,  5,  5,  4,  3,  2])

In [104]:
arr = np.array([11,11,23,34,23,55,4,3,21,21])

In [55]:
np.unique(arr)# prints only single occurence of each element

array([ 3,  4, 11, 21, 23, 34, 55])

In [56]:
#file input output

In [57]:
array = np.array([10,20,30,40,50,60,70,80])

In [61]:
np.save('data',array)#saving the array in a file named "data"

In [62]:
content = np.load('data.npy')#loading the data of that file

In [60]:
content

array([10, 20, 30, 40, 50, 60, 70, 80])

In [63]:
#saving multiple arrays

In [65]:
students =  np.array(['Ali','Sarim','Ahmed','Moosa','Bilal'])
marks = np.array([97,93,91,70,76])

In [75]:
np.savez('arrays',std=students,m=marks)#savez is used for saving multiple arrays into a file

In [76]:
results = np.load('arrays.npz')

In [77]:
results['std']

array(['Ali', 'Sarim', 'Ahmed', 'Moosa', 'Bilal'], dtype='<U5')

In [78]:
results['m']

array([97, 93, 91, 70, 76])

In [ ]:
#linear algebra operations

In [6]:
arr = np.arange(16).reshape(4,4)

In [80]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
arr.diagonal()

array([ 0,  5, 10, 15])

In [8]:
arr.trace()

30

In [10]:
arr1 = np.arange(10,26).reshape((4,4))

In [12]:
arr.dot(arr1)

array([[ 116,  122,  128,  134],
       [ 372,  394,  416,  438],
       [ 628,  666,  704,  742],
       [ 884,  938,  992, 1046]])

In [18]:
from numpy import linalg as ln #importing linear algebra library

In [19]:
#using linear algebra methods

In [25]:
ln.det(arr)#to find determinant

-2.9582283945787796e-30

In [26]:
ln.eig(arr)#method to find eigen values

(array([ 3.24642492e+01, -2.46424920e+00,  4.52933966e-17, -1.52275132e-15]),
 array([[-0.11417645, -0.7327781 ,  0.01936986, -0.48846795],
        [-0.3300046 , -0.28974835,  0.38216644,  0.83598112],
        [-0.54583275,  0.15328139, -0.82244247, -0.20655839],
        [-0.76166089,  0.59631113,  0.42090617, -0.14095478]]))

In [27]:
ln.inv(np.array([[1,5],[9,8]]))#inverse method

array([[-0.21621622,  0.13513514],
       [ 0.24324324, -0.02702703]])

In [29]:
ln.qr(arr)#compute QR composition

(array([[ 0.        , -0.83666003,  0.48308786,  0.25812035],
        [-0.26726124, -0.47809144, -0.8365087 ,  0.01591196],
        [-0.53452248, -0.11952286,  0.22375381, -0.80618499],
        [-0.80178373,  0.23904572,  0.12966702,  0.53215267]]),
 array([[-1.49666295e+01, -1.65701970e+01, -1.81737645e+01,
         -1.97773319e+01],
        [ 0.00000000e+00, -1.19522861e+00, -2.39045722e+00,
         -3.58568583e+00],
        [ 0.00000000e+00,  0.00000000e+00, -1.71941189e-15,
         -5.12511879e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -8.82043219e-16]]))

In [32]:
ln.svd(arr)#compute single value decomposition

(array([[-0.09184212, -0.83160389,  0.52939495,  0.14050262],
        [-0.31812733, -0.44586433, -0.8105844 ,  0.20725087],
        [-0.54441254, -0.06012478,  0.03298396, -0.8360096 ],
        [-0.77069775,  0.32561478,  0.2482055 ,  0.48825611]]),
 array([3.51399637e+01, 2.27661021e+00, 8.80118491e-16, 4.41188001e-17]),
 array([[-0.42334086, -0.47243254, -0.52152422, -0.57061589],
        [ 0.72165263,  0.27714165, -0.16736932, -0.6118803 ],
        [ 0.5427818 , -0.66899815, -0.29034911,  0.41656546],
        [ 0.0734024 , -0.50243554,  0.78466387, -0.35563073]]))

In [ ]:
#random number generation

In [33]:
np.random.normal(3,4,(3,3))

array([[ 4.42454219, -3.14868387,  3.50988262],
       [ 8.34318692, -2.10026493, -2.45446316],
       [ 0.61671251,  6.66934293,  5.03557687]])

In [34]:
np.random.gamma(1,2,(4,4))

array([[2.26605553, 0.41482053, 6.05062269, 0.25531714],
       [0.73991469, 8.27779875, 0.40756713, 1.14047351],
       [0.31488837, 0.02228179, 0.9053312 , 0.23058572],
       [1.80541295, 1.68487661, 1.55678975, 0.09959465]])

In [35]:
#seed

In [46]:
np.random.seed(6) # By setting the seed, you can ensure that the random numbers generated by NumPy are reproducible.

In [47]:
np.random.rand()

0.8928601514360016

In [48]:
#reshape

In [65]:
arr = np.arange(16)

In [66]:
arr.reshape((4,4),order='F')# setting the array shape as columns "fotran style"

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [53]:
arr.reshape((4,4),order='c')# setting the array shape as rows 'c style'

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
#array flatten and ravel

In [58]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [59]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr.flatten()#converts array into one dimension

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr.ravel()#converts array into one dimension

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# difference between ravel and flatten
"""
flatten doesnt effect the real array and makes a copy into single dimension and ravel converts the real array
ravel takes less space and is faster
"""

'\nflatten doesnt effect the real array and makes a copy into single dimension and ravel converts the real array\nravel takes less space and is faster\n'

In [69]:
#concatenation

In [68]:
a =  np.array([[1,2],[3,4]])
b = np.array([[7,8],[9,10]])

In [71]:
np.concatenate((a,b),axis=0)#concatenation of two dimension array axis =0 row wise

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]])

In [72]:
np.concatenate((a,b),axis=1)#concatenation of two dimension array axis =1 column wise wise

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

In [73]:
np.hstack((a,b))# concatenates like axis = 1

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

In [74]:
np.vstack((a,b))# concatenates like axis = 0

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]])

In [75]:
np.r_[a,b] # row wise concatenation

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]])

In [77]:
np.c_[a,b] # column wise concatenation

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

In [78]:
#split

In [95]:
 x = np.array([1,5,66,73,3,4,5,22])

In [96]:
np.split(x,[3])#splits the array from the position mentioned "3"

[array([ 1,  5, 66]), array([73,  3,  4,  5, 22])]

In [97]:
np.split(x,[3,5])# for multiple splits give multiple position it will split from those positions

[array([ 1,  5, 66]), array([73,  3]), array([ 4,  5, 22])]

In [101]:
l = np.arange(2,7,2)

In [102]:
l

array([2, 4, 6])

In [103]:
np.split(x,l)

[array([1, 5]), array([66, 73]), array([3, 4]), array([ 5, 22])]